### ISSUE TITLE
UX Survey Decision Log and Purposes 

### ISSUE THREAD

**Issue by melissamurphy** [hackforla/access-the-data#76] opened 2021-09-23 04:48 UTC
### Dependency
#68 

### Overview
Create a document that delineates the UX survey's goals and how survey questions these goals.

### Action Items
List UX survey questions
For each survey question, note the rationale behind its inclusion
Tie UX survey purposes to the research purposes (described in the UX Research Plan) and other project purposes at large 
Align purposes with rest of team and stakeholders (in FAQ and weekly meeting)

### Resources/Instructions
[UX Survey Purposes and Decision Log](https://docs.google.com/spreadsheets/d/1ybgmhcDt8Esry0ivMZW6HIdzXKFrK2SeCJX2_YZb46M/edit#gid=0)

**Comment by jenny-gih** [comment] 2021-09-25 20:50
Progress: completed screener survey decision log
Blockers: Need Bonnie to review survey questions and decision log
Availability: 5 hours
ETA: by next week if reviewed
Pictures: see link in issue description

**Comment by abryant35** [comment] 2021-10-04 23:30
Closing due to survey questions being confirmed

**Closed by abryant35** 2021-10-04 23:30 UTC
Labels: role: UX/UI, feature: website, dependency, size: 1 pt
