### ISSUE TITLE
Develop Front-End Style Guide 

### ISSUE THREAD

**Issue by lrchang2** [hackforla/access-the-data#40] opened 2021-08-17 15:12 UTC
### Dependencies 
~#26~ 
#39 

### Overview
We need a style guide for the website elements that follows the Access the Data brand guide #39 .

### Action Items
All UI components for the front-end style guide need to be ADA compliant #26 and branding guide #39

- [ ] buttons
- [ ] navigation and sub-navigation menus

### Resources/Instructions
[Web Content Accessibility Guidelines](https://www.w3.org/TR/WCAG20/)
[front end style guides](https://www.nngroup.com/articles/front-end-style-guides/)

[comparative analysis UI for websites](https://www.figma.com/file/6xUSdpvbOMeAuZKRDMSJpy/Access-the-Data-Comp.-analysis?node-id=0%3A1)

All work for Front-End Style guide is condensed in the [current draft of guide](https://docs.google.com/presentation/d/1Fuc_OrS5Jb2ocpDkJJ3bFwdLfYjkUBpwiVKQ1tpePok/edit#slide=id.p). Guide also contains Brand Guide #39 and Content Template Guide #22

**Comment by ExperimentsInHonesty** [comment] 2021-11-16 22:53
Close this is a duplicate of #39

**Closed** 2021-11-16 22:54 UTC
Labels: role: UX/UI, dependency, size: 3 pts, feature: design system
